name: Add generated Go

on:
  pull_request:
    branches: [main]

jobs:
  add-generated-go:
    if: ${{ github.github.triggering_actor != 'GithubActions' }}
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      OWNER: ${{ github.repository_owner }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: generate OpenAPI server
        run: |
          docker run --rm \
            -v "${PWD}:/local" \
            openapitools/openapi-generator-cli generate \
            -i /local/src/openapi/openapi.yaml \
            -o /local/src/go/ \
            -g go-echo-server \
            --git-user-id=${{ env.OWNER }} \
            --git-repo-id=${{ env.REPO_NAME }}
          sudo chown -R runner:docker .
      - name: create go.sum file
        working-directory: src/go
        run: go mod tidy
      - name: configure git
        run: git config --global user.name GithubActions
      - run: ls -la
        working-directory: src/go
      - name: commit new models
        working-directory: src/go
        run: |
          git add go.mod
          git add go.sum
          git add models
      - run: git status
      - run: |
          git commit -m "feat: add generated models"
          git push
