name: Publish

on:
  pull_request:
    branches: [main]
    types: [closed]
permissions:
  contents: write

jobs:
  publish-go:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: generate OpenAPI server
        run: |
          docker run --rm \
            -v "${PWD}:/local" \
            openapitools/openapi-generator-cli generate \
            -i /local/src/openapi/openapi.yaml \
            -o /local/src/go/ \
            -g go-echo-server \
            --git-user-id=FrHorschig \
            --git-repo-id=test
      - name: add models to repo
        run: |
          cd src/go
          git config --global user.name ${{ secretes.GIT_USERNAME }}
          git config --global user.email ${{ secretes.GIT_EMAIL }}
          git add models
          git commit -m "feat: add generated models"
          version=$(grep "openapi:" src/openapi/openapi.yaml | awk '{print $2}')
          git tag v$version
          git push v$version

  publish-ts:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: generate OpenAPI client
        run: |
          docker run --rm \
            -v "${PWD}:/local" \
            openapitools/openapi-generator-cli generate \
            -i /local/"$project"-api/src/openapi/openapi.yaml \
            -o /local/"$project"-api/src/generated-client-ts \
            -g typescript-angular \
            -p npmName="$project"-api \
            -p ngVersion=15.2.0 \
            --git-user-id=FrHorschig \
            --git-repo-id="$project"-api
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
