name: Validate

on:
  pull_request:
    branches: ["main"]

jobs:
  validate:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true && github.github.triggering_actor != 'GithubActions' }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: validate OpenAPI spec
        run: |
          docker run --rm \
            -v $PWD:/work:ro dshanley/vacuum lint \
            src/openapi/openapi.yaml
